### ISSUE TITLE
now.sh a upload

### ISSUE THREAD

**Issue by halilertekin** [Ketcap/Weekend-At-Barnies#2]
heroku kullanmana gerek yok, daha hizli ve kullanisli zeit in now.sh i var
 https://weekend-rcrojzdbry.now.sh gerci projede build hatasi verdi

**Comment by Ketcap** [comment]
927b724a8866a5d855d99e9abe1212a346b0567e ile duzeldiginden tekrar denersen calisicaktir :) Ama client id ayarlarini kendin olusturursan spotifydan now.sh in verdigi adresi eklemen gerekir yoksa calismaz
